services:
  app:
    image: node:22.10-alpine
    command: sh -c "npm install --omit=dev && npm run build && node dist/server/index.js"
    ports:
      - "${PORT}:80"
    working_dir: /app
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - ./:/app
      # Creates empty folder to prevent node_modules from being overwritten by volume
      - /app/node_modules
    environment:
      PORT: 80
